server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true # mustache 파일에서 session과 request에 접근이 가능하도록 해준다.
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL # MODE=MySQL 은 방언(DB Dialect) 설정
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create # ddl - CREATE DROP ALTER TRUNCATE COMMENT
    show-sql: true
    properties:
      hibernate:
        format_sql: true # sql 을 깔끔하게 보이게 하는 코드